title: Mina's Math Art
author: Mina BH Arsanious
email: basiliousmina2@gmail.com
description: That's my awesome math art. I hope you like it. 
social:
  twitter: Mina_Basil
  facebook: profile.php?id=100025042350936
  instagram: mina_basilious
  github: MinaBasilious
  linkedin: mina-basilious

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
